backend:
  name: github
  repo: "hackforla/website-redesign" # Gulp will replace this with your GitHub repository
  branch: "feature/cms" # Branch to update (master by default)

media_folder: "app/images/uploads" # Folder where user uploaded files should go
public_folder: "images/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "app/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Meta Info"
            name: "meta"
            widget: "object"
            fields:
              - label: "Description"
                name: "dek"
                widget: "text"
              - label: "Image"
                name: "image"
                widget: "image"
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "dek"
                widget: "text"
          - label: "Hack Nights Section"
            name: "location"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "dek"
                widget: "text"
              - label: "Locations"
                name: "locations"
                widget: "list"
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "image"
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Date"
                    name: "date"
                    widget: "string"
                  - label: "Address 1"
                    name: "address1"
                    widget: "string"
                  - label: "Address 2"
                    name: "address2"
                    widget: "string"
                  - label: "City"
                    name: "city"
                    widget: "string"
                  - label: "State"
                    name: "state"
                    widget: "string"
                  - label: "Zip"
                    name: "zip"
                    widget: "string"
          - label: "Demographic Stats"
            name: "stats"
            widget: "list"
            fields:
              - label: "Stat Figure"
                name: "figure"
                widget: "string"
              - label: "Stat Description"
                name: "dek"
                widget: "string"
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "dek"
                widget: "text"
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "URL"
                    name: "url"
                    widget: "string"
              - label: "Partner"
                name: "partner"
                widget: "string"
              - label: "Looking For"
                name: "looking"
                widget: "string"
              - label: "Location"
                name: "location"
                widget: "string"
          - label: "Testimonial"
            name: "testimonial"
            widget: "object"
            fields:
              - label: "Quote"
                name: "quote"
                widget: "string"
              - label: "Source"
                name: "source"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
